// Code generated by go generate; DO NOT EDIT.
	// this file was generated by robots at
	// 2018-06-08 14:17:38.164112267 -0600 MDT m=+0.662563022
	// https://github.com/golang/go/raw/master/CONTRIBUTORS
	package contributor

	var Contributors = []string{
			"Carl Chatfield <carlchatfield@gmail.com>",
			"Carl Henrik Lunde <chlunde@ifi.uio.no>",
			"Carl Jackson <carl@stripe.com>",
			"Carl Johnson <me@carlmjohnson.net>",
			"Carl Mastrangelo <notcarl@google.com>",
			"Carl Shapiro <cshapiro@google.com> <cshapiro@golang.org>",
			"Carlisia Campos <carlisia@grokkingtech.io>",
			"Carlo Alberto Ferraris <cafxx@strayorange.com>",
			"Carlos Castillo <cookieo9@gmail.com>",
			"Carlos Cirello <uldericofilho@gmail.com>",
			"Carlos Eduardo Seo <cseo@linux.vnet.ibm.com>",
			"Dustin Carlino <dcarlino@google.com>",
			"Juan Carlos <juanjcsr@gmail.com>",
	}
	